x-veld:
  chain:
    description: "hard-coded evaluation of several spaCy 2.2.4 models. This chain veld is a wrapper 
      of legacy code."
    topic: 
      - "NLP"
      - "Machine Learning"
      - "Named Entity Recognition"

services:
  veld_evaluate:
    build: ./code/
    command: python /veld/code/reevaluate_all_models.py
    volumes:
      - ./code/src/:/veld/code/
      - ./data/spacy-ner/:/veld/input/
      - ./data/spacy-ner/:/veld/output/
    environment:
      out_eval_result_file: "reevaluations_all.md"

